### ISSUE TITLE
Hijri DateTimeRangePicker

### ISSUE THREAD

**Issue by aziz1117** [mominsamir/smHijriDatePicker#1]
It's good but title show month name in Gregorian not in Hijri name. Also if you have option to change number from Hindi to Arabic number.

Thank you

**Comment by mominsamir** [comment]
Hi this is based on local, I have included ar.js local.  You can change local file and picker lauguge will change

**Comment by aziz1117** [comment]
how bower it to my app using  bower install --save smDateTimeRangePicker or
bower install --save smHijriDatePicker

Thanks

**Comment by mominsamir** [comment]
bower install smHijriDatePicker

manually include files to your index page.

if u dont need local file 'ar.js' remove it.

for app use angular.module('your app name', 'ngMaterial','smHijriDatePicker');

**Comment by aziz1117** [comment]
What necessary files should i including into index page?

**Comment by mominsamir** [comment]
all .js and .css files from dist folder.

**Comment by aziz1117** [comment]
Hi,
after i use bower install smHijriDatePicker.
i got in dist folder just those script files vendor.1eb7e3d9.js
and scripts.75f719aa.js and i got those style files vendor.bcd5637e.css
and main.87d45027.css.

**Comment by aziz1117** [comment]
I already include all all .js and .css in dist folder but what directive
should i use to display Hijri calendar?

**Comment by aziz1117** [comment]
I try to use directive in smHijriDatePicker repositories to implement Hijri Date in index file but it does not work.

**Comment by mominsamir** [comment]
```
<div  layout="row"> 
        <sm-date-time-picker 
            fname="field" 
            lable="Date of Birth"
            form="empForm" 
            value="vm.employee.dateOfBirth" 
            flex="50"
            flex-sm="100"
            flex-xs="100"                          
            is-required="{{true}}" 

            format="iYYYY/iM/iD"
            mode="date" 
            week-start-day="Monday">
        </sm-date-time-picker>
</div>
```

This should work, however if it doesn't work can you check if you are getting any error

**Comment by mominsamir** [comment]
And your app should declare like this 
app.module('your module name',[ngMaterial','smHijriDatePicker']);

**Comment by aziz1117** [comment]
It's work perfect but label does not appear on browser.
Could you please guide me how to customize day background-color.

Thank you

**Comment by mominsamir** [comment]
Which label not appearing, can you explain or put screen shot here. 

For bacground color you have  to apply config material theme providers. That should do the trick.

**Comment by aziz1117** [comment]
"Date Of Birth" label does not appear on input text field, I think it
should appear as float label.
