### ISSUE TITLE
Select date not working after saving data on form

### ISSUE THREAD

**Issue by aziz1117** [mominsamir/smHijriDatePicker#2]
I download last version but still not working.
First time lunch form Datepicker work perfect but after saving data to database, second time when i need to select date from Datepicker it's show me error.

![untitled](https://cloud.githubusercontent.com/assets/7342455/14661252/d7a90932-06b4-11e6-8391-f639093d97e3.png)

**Comment by mominsamir** [comment]
i pushed new version, pull that and this issue should be solved

**Comment by aziz1117** [comment]
Still same error. I use  bower install --save smHijriDatePicker.
Should I use bower install --save smDateTimeRangePicker?

**Comment by mominsamir** [comment]
close if this is fixed!
